### ISSUE TITLE
About using Flat UI Pro

### ISSUE THREAD

**Issue by zaherg** [anomalylabs/anomaly-theme#3]
hey, 
I just noticed that you are publishing your less directory with `Flat UI Pro` which is not free nor under MIT license.

am not sure if you got a permission to publish this Paid version of `Flat UI Pro` for the public, I was thinking that you may use [Flat UI](https://github.com/designmodo/Flat-UI) the open source version which is much better if your code is under MIT.

**Comment by RyanThompson** [comment]
Hey there! Good catch, but I believe aside from the license of the addon (which Ill look into) that I am in the clear. I own a developer license for it (same for Redactor which is in the WYSIWYG field type).

**Comment by zaherg** [comment]
yes , but the license does not allow you to put it on github for the public, nor it allow you to `Offer PSD/HTML to users of your hosting or blogging service`.

the developer license allows you to use it in your `Creation of a Theme/Template for CMS for sale` , not to offer it for free, otherwise why people is going to buy it when they can get it for free from another project ?

am just trying to notify you about what I know, and try to help.

thanks

**Comment by RyanThompson** [comment]
I appreciate it! I will have to see about rectifying this for sure. Thanks again!

**Comment by RyanThompson** [comment]
Hey @linuxjuggler thanks again for pointing this out. I looked at the open source version and the only thing I really have AND USE from the Pro in the theme is the GlyphIcons.. which I also have a developers license for. I don't use a lot of the custom elements included so I think Ill remove them.

I think what I will do is change out the verbiage so it's less confusing and remove any of the premium aspects. Might have to move some things into separate non-related packages in FieldTypes but thats OK. I was planning to anyways.
